version: "3.4"

services:
  prometheus:
    image: prom/prometheus:latest
    restart: always
    ports:
      - 9090:9090
    volumes:
      - type: bind
        source: ./prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
        
  grafana:
    image: grafana/grafana
    hostname: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      -  GF_SECURITY_ADMIN_PASSWORD=admin