{
 "title": "Requests x Tenants x Users",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Acessos aos produtos",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(product) (tracking_product_tenants_and_users_total)",
     "legendFormat": "{{product}}"
    }
   ]
  },
  {
   "title": "Requisições x Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Requests x Tenants x Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "tracking_product_tenants_and_users_total",
     "legendFormat": "{{endpoint}}: tenant({{tenant}}) - user({{user}})"
    }
   ]
  },
  {
   "title": "/endpoint1: tenants x users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "tracking_product_tenants_and_users_total{endpoint=\"/metrica/endpoint1\"}",
     "legendFormat": "Tenant: {{tenant}} User: {{user}}"
    }
   ]
  },
  {
   "title": "/endpoint2: tenants x users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "tracking_product_tenants_and_users_total{endpoint=\"/metrica/endpoint2\"}",
     "legendFormat": "Tenant: {{tenant}} User: {{user}}"
    }
   ]
  },
  {
   "title": "Requisições x Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(tracking_product_tenants_and_users_total[1m]) * 60",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}